### ISSUE TITLE
Solution for sub-folder wp installations

### ISSUE THREAD

**Issue by unsalkorkmaz** [WebCreatid/International-Telephone-Input-for-Gravity-Forms#2]
if you try to use this plugin in sub-folder, utils.js file wont call properly. 

Here is a dirty solution:
open **gravityforms-intl-tel-input.php** file, find **gf_iti_js** function and add those lines before closing bracket:

```
	wp_register_script('gf_intlTelInput_utils', plugin_dir_url( __FILE__ ).'intl-tel-input/js/utils.js', array('jquery','intlTelInput'), false, true);
	wp_enqueue_script('gf_intlTelInput_utils');
```

**Comment by amys94fr** [comment]
I fix it thank you
